# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: busybox:latest

before_script:
  - mkdir -vp ~/.ssh
  - eval $(ssh-agent -s)
  - echo "${HOST_NAME}","${HOST_KEY}" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts -v
  - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/key.pem
  - chmod 600 ~/.ssh/key.pem -v

update:
  stage: deploy
  script:
    - ssh -i ~/.ssh/key.pem -rv ${USER}@${HOST_NAME} "cd ${CICD_DIR} && sh ${SCRIPT_FILENAME}.sh"
